twitter_bot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path
from webapp import views

app_name = "webapp"

urlpatterns = [

	path("", views.Home, name="home"),

	path("signup/", views.Signup, name="signup"),
	path("signin/", views.Signin, name="signin"),
	path("signout/", views.Signout, name="signout"),

]

webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class SearchQuery(models.Model):
	user = models.ForeignKey(User, on_delete = models.PROTECT)
	query = models.TextField()
	date_created = models.DateTimeField(default = timezone.now)


class SearchResult(models.Model):
	query_id = models.ForeignKey(SearchQuery, on_delete = models.PROTECT)
	tweet = models.TextField()
	polarity = models.FloatField(null=True)
	polarity_text = models.CharField(max_length = 200)
	subjectivity = models.FloatField(null=True)
	subjectivity_text = models.CharField(max_length = 200)

webapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from webapp.tweet import fetch_tweets_for_query, save_query_and_result
from webapp.models import SearchQuery, SearchResult

import matplotlib.pyplot as plt
import io, urllib, base64


# Create your views here.

@login_required
def Home(request):
	query = request.GET.get('query', '')
	tweet_list = []
	uri = ""

	if query:
		if not SearchQuery.objects.filter(user = request.user.id, query = query).exists():
			tweets = fetch_tweets_for_query(query)
			if tweets:
				tweet_list = save_query_and_result(request.user.id, query, tweets)
			else:
				messages.warning(request, 'Tweet result not found for query search %s' % query )
		else:
			tweet_list = SearchResult.objects.filter(query_id__user = request.user.id, query_id__query = query)

		if tweet_list:
			positive = 0
			netural = 0
			negative = 0
			for i in tweet_list:
				positive += 1 if float(i.polarity) > 0 else 0
				netural += 1 if float(i.polarity) == 0 else 0
				negative += 1 if float(i.polarity) < 0 else 0

			labels=['Positive Tweets','Neutral Tweets','Negative Tweets']
			colors=['green','blue','red']
			exp=(0.07,0,0)
			result = [positive, netural, negative]

			plt.pie(result,colors=colors,labels=labels,shadow=True,explode=exp,autopct='%1.1f%%')
			plt.title('Sentiment Analysis')
			figure = plt.gcf()

			buff = io.BytesIO()
			figure.savefig(buff, format="png")
			buff.seek(0)
			string = base64.b64encode(buff.read())
			uri = urllib.parse.quote(string)

	recent_search = SearchQuery.objects.filter(user = request.user.id)
	return render(request, "webapp/index.html", {'recent_search': recent_search, 'tweets': tweet_list, 'uri':uri})


def Signup(request):

	if request.user.is_authenticated:
		return redirect('webapp:home')

	if request.method == 'POST':
		form = UserCreationForm(request.POST)

		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username = username,password = password)
			login(request, user)
			return redirect('webapp:home')

		else:
			return render(request,'webapp/registration.html',{'form':form})

	else:
		form = UserCreationForm()
		return render(request,'webapp/registration.html',{'form':form})



def Signin(request):
    if request.user.is_authenticated:
        return redirect('/')
     
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
 
        if user is not None:
            login(request,user)
            return redirect('webapp:home')
        else:
        	messages.warning(request, "Incorrect username or password")
        	return render(request,'webapp/login.html')
    else:
        return render(request, 'webapp/login.html')


@login_required
def Signout(request):
    logout(request)
    return redirect('webapp:signin')

templates/webapp/index.html
<!doctype html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Twitter world</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar" style="background-color: #db4a1e">
          <div class="container-fluid">
            <a class="navbar-brand"></a>
            <form class="d-flex" role="search">
              <a href="{% url 'webapp:signout' %}" class="btn btn-sm btn-secondary font-weight-bold top-0">Logout</a>
            </form>
          </div>
        </nav>
        <div class="d-flex flex-column justify-content-center align-items-center" style="background-color: #db4a1e;height: 50vh;">
            <img class="img-fluid" src="{% static 'img/twitter.png' %}" style="height: 90px;">
            <h2 class="text-white">
                Welcome to the DZ world
            </h2>
            <form class="input-group mt-3 w-50" action="" method="GET">
                    <input type="text" name="query" class="form-control p-2 rounded-left" required placeholder="Search your ">
                    <button class="btn btn-secondary rounded-right" type="submit">Search</button>
            </form>
        </div>
        <div>
            <h3 class="font-weight-bold text-center mt-4">
                Recent search
            </h3>
            <div class="container mt-5">
                <div class="row">
                    {% for i in recent_search %}
                    <div class="col-2 mb-3">
                        <a href="{% url 'webapp:home' %}?query={{ i.query }}">
                            <span class="badge border border-primary text-dark p-2 px-4">{{ i.query }}</span>
                        </a>
                    </div>
                    {% empty %}
                    <div class="col-12 mb-3 bg-secondary">
                        <div class="d-flex flex-column justify-content-center align-items-center py-3">
                            <img src="{% static 'img/eye.png' %}" style="width: 200px;">
                            <p class="mt-3 text-white">
                                Sorry, we coulden't find any recent searches.
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="container-fluid mt-5">
                {% if uri %}
                <div class="text-center">
                    <img src="data:image/png;base64,{{uri}}" style="width: 500px;">
                </div>
                {% endif %}
                {% if tweets %}
                <div class="row">
                    <table class="table table-hover text-center">
                        <thead>
                            <tr>
                                <th scope="col" colspan="4">Tweet Analysis</th>
                            </tr>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Query</th>
                                <th scope="col">Polarity</th>
                                <th scope="col">Subjectivity</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in tweets %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ i.tweet }}</td>
                                <td>{{ i.polarity_text }}</td>
                                <td>{{ i.subjectivity_text }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>

templates/webapp/login.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login page</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
    <body class="text-center" style="background-color: #db4a1e;">
            <div class="d-flex flex-column justify-content-center align-items-center h-100">
                <div class="border border-white p-4 rounded">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <img class="mb-4" src="{% static 'img/twitter.png' %}" alt="" width="95" height="90">
                        <h1 class="h3 mb-3 fw-normal text-white">Please sign in</h1>
                        {% for message in messages %}
                        <p class="text-danger">{{ message }}</p>
                        {% endfor %}
                        <div class="mt-3">
                            <input type="email" name="username" class="form-control" placeholder="name@example.com" required>
                        </div>
                        <div class="mt-3">
                            <input type="password" name="password" class="form-control" placeholder="Password" required>
                        </div>
                        <div class="checkbox my-3">
                            <label class="text-white">
                                <input type="checkbox" value="remember-me"> Remember me
                            </label>
                        </div>
                        <button class="w-100 btn btn-lg btn-secondary" type="submit">Sign in</button>
                        <p class="mt-5 mb-3 text-muted text-white">Create a new account <a href="{% url 'webapp:signup' %}" class="text-white">Signup here</a></p>
                    </form>
                </div>
            </div>
    </body>
</html>

templates/webapp/registration.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registration page</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
    <body class="text-center" style="background-color: #db4a1e;">
            <div class="d-flex flex-column justify-content-center align-items-center h-100">
                <div class="border border-white p-4 rounded">
                    <form action="" method="POST">
                        {% csrf_token %}

                        <img class="mb-4" src="{% static 'img/twitter.png' %}" alt="" width="95" height="90">
                        <h1 class="h3 mb-3 fw-normal text-white">Please sign up</h1>

                        {{ form.non_field_errors }}
                        
                        <div class="mt-3">
                            <input type="email" class="form-control" name="username" placeholder="Please enter email" required value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
                            <p class="text-left text-danger">{{ form.username.errors.0 }}</p>
                        </div>
                        <div class="mt-3">
                            <input type="password" name="password1" class="form-control" placeholder="Please enter password" required>
                            <p class="text-left text-danger">{{ form.password1.errors.0 }}</p>
                        </div>
                        <div class="mt-3">
                            <input type="password" name="password2" class="form-control" placeholder="Please confirm password" required>
                            <p class="text-left text-danger">{{ form.password2.errors.0 }}</p>
                        </div>
                        <div class="checkbox my-3">
                            <label class="text-white">
                                <input type="checkbox" value="remember-me"> Remember me
                            </label>
                        </div>
                        <button class="w-100 btn btn-lg btn-secondary" type="submit">Sign up</button>
                        <p class="mt-5 mb-3 text-muted text-white">Account already exists? <a href="{% url 'webapp:signin' %}" class="text-white">login here</a></p>
                    </form>
                </div>
            </div>
    </body>
</html>